config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  get 'locations/current', :controller => 'locations', :action => 'current'
  get 'locations/server', :controller => 'locations', :action => 'server'
  get 'ping_results/recent', :controller => 'ping_results', :action => 'recent'
  resources :ping_results, :only => [:create, :show]

  if Rails.env.development? or Rails.env.test? or ENV['APP_STATUS'] =~ /staging/
    resources :locations
    resources :ping_results
  end

end

app/models/ping_result.rb
require 'ipaddr'

class PingResult < ActiveRecord::Base
  include ApplicationHelper
  belongs_to :location
  validates_numericality_of :lag_ms, greater_than_or_equal_to: 0.0
  validates :location_id, numericality: { only_integer: true }
  validates :server_location_id, numericality: { only_integer: true }

  def distance
    c = Location.find(location_id)
    return nil unless c and c.geocoded?
    s = Location.find(server_location_id)
    return nil unless s and s.geocoded?
    return Geocoder::Calculations.distance_between(
      [c.longitude, c.latitude],
      [s.longitude, s.latitude],
      :units => :km
    )
  end

  def measure_distance!
    self.distance_km = distance
  end
end

app/controllers/ping_results_controller.rb
class PingResultsController < ApplicationController
  include Requested
  before_action :set_ping_result, only: [:show, :edit, :update, :destroy]

  # GET /ping_results/recent
  def recent
    server = Location.where(host: host_on_header).order(updated_at: :desc).first
    @ping_results = server ? PingResult.where(server_location_id: server.id).where.not(distance_km: nil).order(updated_at: :desc).limit(100) : []
  end

  # GET /ping_results
  # GET /ping_results.json
  def index
    @ping_results = PingResult.all
  end

  # GET /ping_results/1
  # GET /ping_results/1.json
  def show
  end

  # GET /ping_results/new
  def new
    @ping_result = PingResult.new
  end

  # GET /ping_results/1/edit
  def edit
  end

  # POST /ping_results
  # POST /ping_results.json
  def create
    @ping_result = PingResult.new(ping_result_params)
    @ping_result.user_agent = user_agent_on_header
    @ping_result.protocol = protocol_on_request
    @ping_result.distance_km = nil

    respond_to do |format|
      if check_and_create
        format.html { redirect_to @ping_result, notice: 'Ping result was successfully created.' }
        format.json { render :show, status: :created, location: @ping_result }
      else
        format.html { render :new }
        format.json { render json: @ping_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ping_results/1
  # PATCH/PUT /ping_results/1.json
  def update
    respond_to do |format|
      if @ping_result.update(ping_result_params)
        format.html { redirect_to @ping_result, notice: 'Ping result was successfully updated.' }
        format.json { render :show, status: :ok, location: @ping_result }
      else
        format.html { render :edit }
        format.json { render json: @ping_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ping_results/1
  # DELETE /ping_results/1.json
  def destroy
    @ping_result.destroy
    respond_to do |format|
      format.html { redirect_to ping_results_url, notice: 'Ping result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ping_result
      @ping_result = PingResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ping_result_params
      params.require(:ping_result).permit(:lag_ms, :user_agent, :location_id, :server_location_id, :protocol, :distance_km)
    end

    # Measure the distance and update the @ping_result after validation
    def check_and_create
      client = Location.where(host: src_addr_on_header).order(updated_at: :desc).first
      return false if not client or client.id != @ping_result.location_id
      server = Location.where(host: host_on_header).order(updated_at: :desc).first
      return false if not server or server.id != @ping_result.server_location_id
      @ping_result.measure_distance!
      return @ping_result.save
    end
end

app/helpers/ping_results_helper.rb
module PingResultsHelper
end

app/views/ping_results/_form.html.erb
<%= javascript_include_tag "ping" %>
<%= javascript_tag do %>
  $("#ping").click(function() {
    $("#ping_result_lag_ms").val("");
    $("#ping_result_ping_progress").html("");
    Pinger.measure("<%= path_to_javascript "ping" %>",
      function(lag){$("#ping_result_ping_progress").append(" " + lag);},
      function(lag){$("#ping_result_lag_ms").val(lag);}
    )});
<% end %>

<%= form_for(@ping_result) do |f| %>
  <% if @ping_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ping_result.errors.count, "error") %> prohibited this ping_result from being saved:</h2>

      <ul>
      <% @ping_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lag_ms %><br>
    <%= f.text_field :lag_ms %>
    <a href="#" id="ping">Ping!</a>
    <span id="ping_result_ping_progress"></span>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :server_location_id %><br>
    <%= f.text_field :server_location_id %>
  </div>
  <div class="field">
    <%= f.label :protocol %><br>
    <%= f.text_field :protocol %>
  </div>
  <div class="field">
    <%= f.label :distance_km %><br>
    <%= f.text_field :distance_km %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ping_results/edit.html.erb
<h1>Editing Ping Result</h1>

<%= render 'form' %>

<%= link_to 'Show', @ping_result %> |
<%= link_to 'Back', ping_results_path %>

app/views/ping_results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ping Results</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Lag ms</th>
      <th>User agent</th>
      <th>Location id</th>
      <th>Server location id</th>
      <th>Protocol</th>
      <th>Distance km</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ping_results.each do |ping_result| %>
      <tr>
        <td><%= ping_result.id %></td>
        <td><%= ping_result.lag_ms %></td>
        <td><%= ping_result.user_agent %></td>
        <td><%= ping_result.location_id %></td>
        <td><%= ping_result.server_location_id %></td>
        <td><%= ping_result.protocol %></td>
        <td><%= ping_result.distance_km %></td>
        <td><%= link_to 'Show', ping_result %></td>
        <td><%= link_to 'Edit', edit_ping_result_path(ping_result) %></td>
        <td><%= link_to 'Destroy', ping_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ping result', new_ping_result_path %>

app/views/ping_results/new.html.erb
<h1>New Ping Result</h1>

<%= render 'form' %>

<%= link_to 'Back', ping_results_path %>

app/views/ping_results/recent.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recent Ping Results</h1>

<table>
  <thead>
    <tr>
      <th>Lag ms</th>
      <th>Distance km</th>
    </tr>
  </thead>

  <tbody>
    <% @ping_results.each do |ping_result| %>
      <tr>
        <td><%= ping_result.lag_ms %></td>
        <td><%= ping_result.distance_km %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ping result', new_ping_result_path %>

app/views/ping_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @ping_result.id %>
</p>

<p>
  <strong>Lag ms:</strong>
  <%= @ping_result.lag_ms %>
</p>

<p>
  <strong>User agent:</strong>
  <%= @ping_result.user_agent %>
</p>

<p>
  <strong>Location id:</strong>
  <%=
    if @ping_result.location_id
      link_to @ping_result.location_id, @ping_result.location
    else
      nil
    end
  %>
</p>

<p>
  <strong>Server location id:</strong>
  <%=
    if @ping_result.server_location_id
      link_to @ping_result.server_location_id, Location.find(@ping_result.server_location_id)
    else
      nil
    end
   %>
</p>

<p>
  <strong>Protocol:</strong>
  <%= @ping_result.protocol %>
</p>

<p>
  <strong>Distance km:</strong>
  <%= @ping_result.distance_km %>
</p>

<%= link_to 'Edit', edit_ping_result_path(@ping_result) %> |
<%= link_to 'Back', ping_results_path %>