config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  get 'locations/current', :controller => 'locations', :action => 'current'
  get 'locations/server', :controller => 'locations', :action => 'server'
  get 'ping_results/recent', :controller => 'ping_results', :action => 'recent'
  resources :ping_results, :only => [:create, :show]

  if Rails.env.development? or Rails.env.test? or ENV['APP_STATUS'] =~ /staging/
    resources :locations
    resources :ping_results
  end

end

app/models/location.rb
require 'resolv'

class Location < ActiveRecord::Base
  include ApplicationHelper
  validates :host, presence: true
  has_many :ping_results

  Expires_after = 86400 # sec

  @@geocoder = Geocoder
  def Location::geocoder=(klass)
    @@geocoder = klass
  end

  @@resolver = Resolv
  def Location::resolver=(klass)
    @@resolver = klass
  end

  def geocode_from_host!
    ipaddress = host
    unless ipaddress =~ VALID_IPADDR_REGEX
      ipaddress = @@resolver.getaddress(ipaddress)
    end
    r = @@geocoder.search(ipaddress, ip_address: true).first
    if r and r.respond_to?(:data) and r.data['country_code'] != 'RD'
      logger.info "Geocoded from host: #{r.inspect}"
      obtain_geocode_result(r) if r.data['ip']
      # IP address is assumed to be geocoded if there is 'ip' set
    end
    return r
  end

  def geocode_from_city!
    r = @@geocoder.search(city).first
    logger.info "Geocoded from city: #{r.inspect}" if r
    obtain_geocode_result(r)
    return r
  end

  def geocode!
    r = geocode_from_host!
    if not geocoded? and not city.blank?
      r = geocode_from_city!
    end
    return r
  end

  def geocoded?
    return false if self.city.blank?
    return false unless self.latitude.is_a?(Numeric)
    return false unless self.longitude.is_a?(Numeric)
    return true
  end

  def expired?(time = Time.now)
    return false unless self.updated_at
    return false if self.updated_at > time - Location::Expires_after
    return true
  end

  private
  def obtain_geocode_result(result)
    if result
      if result.data['country'] == 'US'
        self.city = "#{result.data['city']}, #{result.data['region']}, #{result.data['country']}".sub(/^[ ,]*/, "")
      elsif not result.address.blank?
        self.city = result.address
      elsif not result.city.blank?
        self.city = result.city
      end
      self.latitude = result.latitude
      self.longitude = result.longitude
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  include Requested
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  @@geocodejob = GeocodeJob
  def LocationsController::geocodejob=(klass)
    @@geocodejob = klass
  end
  def LocationsController::geocodejob
    @@geocodejob
  end

  # GET /locations/current
  # GET /locations/current.json
  def current
    @location = Location.where(host: src_addr_on_header).order(updated_at: :desc).first
    if not @location or @location.expired?
      @location = Location.new(host: src_addr_on_header)
      @location.save! # assign an id to be presneted to the front end
      @@geocodejob.perform_later(id: @location.id)
    end
    render :host, layout: false
  end

  # GET /locations/server
  # GET /locations/server.json
  def server
    @location = Location.where(host: host_on_header).order(updated_at: :desc).first
    if not @location	# Server location does not expire
      @location = Location.new(host: host_on_header)
      @location.save! # assign an id to be presneted to the front end
      @@geocodejob.perform_later(id: @location.id)
    end
    render :host, layout: false
  end

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
    @location.host = src_addr_on_header
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @@geocodejob.perform_later(location_params)

    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was enqued.' }
      format.json { render :show, status: :ok } # FIXME
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:host, :latitude, :longitude, :city)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :host %><br>
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/host.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @location.id %>
</p>

<p>
  <strong>Host:</strong>
  <%= @location.host %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Host</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.id %></td>
        <td><%= location.host %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.city %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Host:</strong>
  <%= @location.host %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<table>
  <thead>
    <tr>
      <th>Lag ms</th>
      <th>Ping result id</th>
    </tr>
  </thead>

  <tbody>
    <% @location.ping_results.each do |ping_result| %>
      <tr>
        <td><%= ping_result.lag_ms %></td>
        <td><%= link_to ping_result.id, ping_result %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>